include $(THEOS)/makefiles/common.mk

TWEAK_NAME = TypeStatusRelay

TypeStatusRelay_FILES = IMAgentRelay.x ../HBTSConversationPreferences.m
TypeStatusRelay_LIBRARIES = cephei
TypeStatusRelay_CFLAGS = -include ../Global.h
TypeStatusRelay_USE_SUBSTRATE = 0

include $(THEOS_MAKE_PATH)/tweak.mk
